# Jekyll configuration

name: MadStrawberry's Blog
description: 3D Engine Developer

# Url is currently only used only for the RSS feed in feed.xml
url: http://FrankPIE.github.io

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

showproject: true

author: MadStrawberry
copyright: 2015-2019

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: FrankPIE
  stackoverflow: '4806840'
  zhihu: 'madstrawberry'
  linkedin: 'peibx'
  instagram: 
  lastfm: 
  rss: feed.xml

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate                     : 7
paginate_path                : 'page:num'

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:
# Baidu Analytics key, leave blank to ignore
baidu_analytics_key: '01682caa07cbded0846065f71805072f'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: madstrawberry-space-1
comments: true

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
